-- hds header_start
--
-- VHDL Entity eng_bassam.all_block.symbol
--
-- Created:
--          by - ahmed.UNKNOWN (AHMEDSAMY)
--          at - 23:04:53 02/27/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY all_block IS
   PORT( 
      clk        : IN     std_logic;
      clk1       : IN     std_logic;
      key        : IN     std_logic_vector (127 DOWNTO 0);
      kin        : IN     std_logic_vector (63 DOWNTO 0);
      plaintext  : IN     std_logic_vector (63 DOWNTO 0);
      rst        : IN     std_logic;
      rst1       : IN     std_logic;
      typ        : IN     std_logic;
      ciphertext : OUT    std_logic_vector (63 DOWNTO 0)
   );

-- Declarations

END all_block ;

-- hds interface_end
--
-- VHDL Architecture eng_bassam.all_block.struct
--
-- Created:
--          by - ahmed.UNKNOWN (AHMEDSAMY)
--          at - 23:04:53 02/27/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


LIBRARY eng_bassam;

ARCHITECTURE struct OF all_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL en   : std_logic;
   SIGNAL o2   : std_logic;
   SIGNAL out1 : std_logic;
   SIGNAL y    : std_logic_vector(63 DOWNTO 0);


   -- Component Declarations
   COMPONENT encre
   PORT (
      plaintext  : IN     std_logic_vector (63 DOWNTO 0);
      k1         : IN     std_logic_vector (63 DOWNTO 0);
      --k2		     :in std_logic_vector(15 downto 0);
      clk        : IN     std_logic ;
      --k2		     :in std_logic_vector(15 downto 0);
      rst        : IN     std_logic ;
      typ        : IN     std_logic ;
      en         : OUT    std_logic ;
      ciphertext : OUT    std_logic_vector (63 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT key2
   PORT (
      key  : IN     std_logic_vector (127 DOWNTO 0);
      kin  : IN     std_logic_vector (63 DOWNTO 0);
      en   : IN     std_logic ;
      typ1 : IN     std_logic ;
      clk  : IN     std_logic ;
      rst  : IN     std_logic ;
      y    : OUT    std_logic_vector (63 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT typ
   PORT (
      x  : IN     std_logic ;
      o1 : OUT    std_logic ;
      o2 : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : encre USE ENTITY eng_bassam.encre;
   FOR ALL : key2 USE ENTITY eng_bassam.key2;
   FOR ALL : typ USE ENTITY eng_bassam.typ;
   -- pragma synthesis_on


BEGIN
   -- Instance port mappings.
   I0 : encre
      PORT MAP (
         plaintext  => plaintext,
         k1         => y,
         clk        => clk,
         rst        => rst,
         typ        => o2,
         en         => en,
         ciphertext => ciphertext
      );
   I1 : key2
      PORT MAP (
         key  => key,
         kin  => kin,
         en   => en,
         typ1 => out1,
         clk  => clk1,
         rst  => rst1,
         y    => y
      );
   I2 : typ
      PORT MAP (
         x  => typ,
         o1 => out1,
         o2 => o2
      );

END struct;
