-- hds header_start
--
-- VHDL Architecture eng_bassam.first_control.rtl
--
-- Created:
--          by - ahmed.UNKNOWN (AHMEDSAMY)
--          at - 14:45:44 01/31/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY first_control IS
-- Declarations

	port(
		  	plaintext,k1,k2,k3 :in std_logic_vector(63 downto 0);
			clk : std_logic;
			ciphertext : out std_logic_vector(63 downto 0)
		);
END first_control ;
-- hds interface_end
ARCHITECTURE rtl OF first_control IS

	signal data :std_logic_vector(63 downto 0);
	signal s1,s2,s3,s4 : std_logic_vector(15 downto 0);
	signal index :unsigned (1 downto 0);
--------------------------------for xor -------------------------------	
--	signal p1,p2,p3,p4 : std_logic_vector(15 downto 0);

BEGIN
	data <= plaintext xor k1;
	s1 <=data(15 downto 0);
	s2 <=data(31 downto 16);
	s3 <=data(47 downto 32);
	s4 <=data(63 downto 48);
	---------------------------------------------change value-------------------------------------------------
	index <= (others =>'0');
	---------------for  s1------------------------
	process(clk)
	BEGIN
	if (rising_edge(clk)) then
		if index < 4 then
			if (s1(3 downto 0) = "0000")then
				s1(3 downto 0)<= "0010";
			elsif (s1(3 downto 0) = "0001")then
				s1(3 downto 0)<= "0011";
			elsif (s1(3 downto 0) = "0010")then
				s1(3 downto 0)<= "0000";
			elsif (s1(3 downto 0) = "0011")then
				s1(3 downto 0)<= "0001";
			elsif (s1(3 downto 0) = "0100")then
				s1(3 downto 0)<= "1011";
			elsif (s1(3 downto 0) = "0101")then
				s1(3 downto 0)<= "1110";
			elsif (s1(3 downto 0) = "0110")then
				s1(3 downto 0)<= "1010";
			elsif (s1(3 downto 0) = "0111")then
				s1(3 downto 0)<= "1101";
			elsif (s1(3 downto 0) = "1000")then
				s1(3 downto 0)<= "1111";
			elsif (s1(3 downto 0) = "1001")then
				s1(3 downto 0)<= "1100";
			elsif (s1(3 downto 0) = "1010")then
				s1(3 downto 0)<= "0110";
			elsif (s1(3 downto 0) = "1011")then
				s1(3 downto 0)<= "0100";
			elsif (s1(3 downto 0) = "1100")then
				s1(3 downto 0)<= "1001";
			elsif (s1(3 downto 0) = "1101")then
				s1(3 downto 0)<= "0111";
			elsif (s1(3 downto 0) = "1110")then
				s1(3 downto 0)<= "0101";
			elsif (s1(3 downto 0) = "1111")then
				s1(3 downto 0)<= "1000";
			end if;
 			index <= index + 1;
 		end if ;
	end if ;
	end process;
	---------------------------------------------after p------------------------------------------------------

END rtl;
