-- hds header_start
--
-- VHDL Entity eng_bassam.first.symbol
--
-- Created:
--          by - ahmed.UNKNOWN (AHMEDSAMY)
--          at - 11:13:05 02/28/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY first IS
   PORT( 
      key        : IN     std_logic_vector (127 DOWNTO 0);
      kin        : IN     std_logic_vector (63 DOWNTO 0);
      plaintext  : IN     std_logic_vector (63 DOWNTO 0);
      ciphertext : OUT    std_logic_vector (63 DOWNTO 0)
   );

-- Declarations

END first ;

-- hds interface_end
--
-- VHDL Architecture eng_bassam.first.struct
--
-- Created:
--          by - ahmed.UNKNOWN (AHMEDSAMY)
--          at - 11:13:05 02/28/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


LIBRARY eng_bassam;

ARCHITECTURE struct OF first IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk : std_logic;
   SIGNAL en  : std_logic;
   SIGNAL rst : std_logic;
   SIGNAL y   : std_logic_vector(63 DOWNTO 0);


   -- Component Declarations
   COMPONENT key3
   PORT (
      key : IN     std_logic_vector (127 DOWNTO 0);
      kin : IN     std_logic_vector (63 DOWNTO 0);
      en  : IN     std_logic ;
      clk : IN     std_logic ;
      rst : IN     std_logic ;
      y   : OUT    std_logic_vector (63 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT test3
   PORT (
      plaintext  : IN     std_logic_vector (63 DOWNTO 0);
      k1         : IN     std_logic_vector (63 DOWNTO 0);
      --k2		     :in std_logic_vector(15 downto 0);
      clk        : IN     std_logic ;
      --k2		     :in std_logic_vector(15 downto 0);
      rst        : IN     std_logic ;
      en         : OUT    std_logic ;
      ciphertext : OUT    std_logic_vector (63 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : key3 USE ENTITY eng_bassam.key3;
   FOR ALL : test3 USE ENTITY eng_bassam.test3;
   -- pragma synthesis_on


BEGIN
   -- Instance port mappings.
   I1 : key3
      PORT MAP (
         key => key,
         kin => kin,
         en  => en,
         clk => clk,
         rst => rst,
         y   => y
      );
   I0 : test3
      PORT MAP (
         plaintext  => plaintext,
         k1         => y,
         clk        => clk,
         rst        => rst,
         en         => en,
         ciphertext => ciphertext
      );

END struct;
