-- hds header_start
--
-- VHDL Entity eng_bassam.new_decr.symbol
--
-- Created:
--          by - ahmed.UNKNOWN (AHMEDSAMY)
--          at - 10:50:55 07/14/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY new_decr IS
   PORT( 
      clk        : IN     std_logic;
      clk1       : IN     std_logic;
      key        : IN     std_logic_vector (127 DOWNTO 0);
      kin        : IN     std_logic_vector (63 DOWNTO 0);
      plaintext  : IN     std_logic_vector (63 DOWNTO 0);
      rst        : IN     std_logic;
      rst1       : IN     std_logic;
      typ1       : IN     std_logic;
      typ2       : IN     std_logic;
      ciphertext : OUT    std_logic_vector (63 DOWNTO 0)
   );

-- Declarations

END new_decr ;

-- hds interface_end
--
-- VHDL Architecture eng_bassam.new_decr.struct
--
-- Created:
--          by - ahmed.UNKNOWN (AHMEDSAMY)
--          at - 10:50:55 07/14/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


LIBRARY eng_bassam;

ARCHITECTURE struct OF new_decr IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL en : std_logic;
   SIGNAL k1 : std_logic_vector(63 DOWNTO 0);


   -- Component Declarations
   COMPONENT Decryption11
   PORT (
      plaintext  : IN     std_logic_vector (63 DOWNTO 0);
      k1         : IN     std_logic_vector (63 DOWNTO 0);
      --k2		     :in std_logic_vector(15 downto 0);
      clk        : IN     std_logic ;
      --k2		     :in std_logic_vector(15 downto 0);
      rst        : IN     std_logic ;
      typ2       : IN     std_logic ;
      en         : OUT    std_logic ;
      ciphertext : OUT    std_logic_vector (63 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT key2
   PORT (
      key  : IN     std_logic_vector (127 DOWNTO 0);
      kin  : IN     std_logic_vector (63 DOWNTO 0);
      en   : IN     std_logic ;
      typ1 : IN     std_logic ;
      clk  : IN     std_logic ;
      rst  : IN     std_logic ;
      y    : OUT    std_logic_vector (63 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Decryption11 USE ENTITY eng_bassam.Decryption11;
   FOR ALL : key2 USE ENTITY eng_bassam.key2;
   -- pragma synthesis_on


BEGIN
   -- Instance port mappings.
   I0 : Decryption11
      PORT MAP (
         plaintext  => plaintext,
         k1         => k1,
         clk        => clk,
         rst        => rst,
         typ2       => typ2,
         en         => en,
         ciphertext => ciphertext
      );
   I1 : key2
      PORT MAP (
         key  => key,
         kin  => kin,
         en   => en,
         typ1 => typ1,
         clk  => clk1,
         rst  => rst1,
         y    => k1
      );

END struct;
