-- hds header_start
--
-- VHDL Architecture eng_bassam.test.rtl
--
-- Created:
--          by - ahmed.UNKNOWN (AHMEDSAMY)
--          at - 21:23:54 02/12/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY test1 IS
-- Declarations
		 	port(
		  	x:in std_logic_vector(3 downto 0);
			clk : in std_logic;
			y : out std_logic_vector(3 downto 0)
		);
END test1 ;

-- hds interface_end
ARCHITECTURE rtl OF test1 IS
   signal s: std_logic_vector(3 downto 0);
   signal rst:unsigned (0 downto 0);
BEGIN
process(x,clk,rst)
BEGIN
  rst<= (others =>'0');
  if(rst = 0)then
  	s<=x(3 downto 0);
	rst<=rst+1;
  elsif(rst = 1)then
   	s<= s(1)&s(0)&s(3)&s(2);
    rst<=rst+1;
end if;
end process;
END rtl;
