-- hds header_start
--
-- VHDL Architecture eng_bassam.typ.rtl
--
-- Created:
--          by - ahmed.UNKNOWN (AHMEDSAMY)
--          at - 22:39:04 02/27/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2001.5 (Build 170)
--
-- hds header_end
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY typ IS
-- Declarations
	   port (
	   		x  : in  std_logic;
	   		o1,o2  : out std_logic	 
	   			);
END typ ;

-- hds interface_end
ARCHITECTURE rtl OF typ IS
BEGIN
	o1 <= x ;
	o2 <= x ;
END rtl;
